'use strict';
function showImport(job){const s=job.import_summary;const node=document.getElementById('import-summary');node.hidden=!s;if(s)node.textContent=`Analisi Excel completata: ${s.sheets_read} fogli, ${s.cases} obiettivi, ${s.glossary_terms} termini, ${s.dev_keys} dev key, ${s.log_keys} log key. Report: ${s.report_sheets.join(', ')||'solo video'}${s.fallback_report?' (formato di fallback: nessun formato cliente fornito)':''}.`;}
const API='http://127.0.0.1:18766';
const $=id=>document.getElementById(id);
let token=sessionStorage.getItem('lqa-token')||'',file=null,game='',busy=false,polling=false,companionVersion='';
function compatible(){const v=companionVersion.split('.').map(Number);return v[0]>0||(v[0]===0&&v[1]>=5);}
function notice(text){$('notice').textContent=text;$('notice').hidden=!text;}
function connected(ok){$('connection').classList.toggle('connected',ok);$('connection').innerHTML=ok?'<i></i>PC collegato':'<i></i>PC non collegato';$('connect-card').hidden=ok;$('start').disabled=!ok||busy||!compatible();}
async function request(path,options={}){
 const headers={...options.headers};if(token)headers.Authorization='Bearer '+token;
 const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),path==='/jobs'||path.startsWith('/download/')?120000:path==='/device'?45000:15000);
 let r;try{r=await fetch(API+path,{...options,headers,signal:controller.signal,targetAddressSpace:'loopback'});}catch(e){throw new Error('Collegamento non completato. Apri il componente LQA Pilot e consenti l’accesso alla rete locale. Se il browser integrato resta bloccato, apri questo sito in Chrome o Edge.');}finally{clearTimeout(timeout);}
 if(r.status===401){token='';sessionStorage.removeItem('lqa-token');connected(false);}
 if(!r.ok){const data=await r.json().catch(()=>({}));throw new Error(data.error||'Operazione non riuscita');}
 return r;
}
$('pair-form').addEventListener('submit',async e=>{e.preventDefault();notice('Collegamento in corso. Se richiesto, consenti al browser l’accesso alla rete locale.');try{const r=await request('/pair',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code:$('pair-code').value.trim().toUpperCase()})});token=(await r.json()).token;sessionStorage.setItem('lqa-token',token);connected(true);notice('');await poll();}catch(e){notice(e.message);}});
function selectFile(f){file=null;if(!f)return;if(!f.name.toLowerCase().endsWith('.xlsx')||f.size>30*1024*1024){notice('Seleziona un file .xlsx di massimo 30 MB.');return;}file=f;$('file-label').textContent=f.name;$('file-detail').textContent=(f.size/1024/1024).toFixed(1)+' MB · Pronto per l’analisi';$('dropzone').classList.add('selected');notice('');}
$('workbook').addEventListener('change',e=>selectFile(e.target.files[0]));
for(const event of ['dragenter','dragover'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.add('drag');});
for(const event of ['dragleave','drop'])$('dropzone').addEventListener(event,e=>{e.preventDefault();$('dropzone').classList.remove('drag');if(event==='drop'){const files=e.dataTransfer.files;if(files.length){$('workbook').files=files;selectFile(files[0]);}}});
$('language').addEventListener('change',()=>{$('other-language').hidden=$('language').value!=='other';$('other-language').required=$('language').value==='other';});
document.querySelectorAll('[name=mode]').forEach(el=>el.addEventListener('change',()=>{$('output-hint').textContent=el.value==='video'?'Solo i video dei journey. Nessuna analisi LQA o segnalazione di bug.':'Solo i fogli bug originali, con screenshot, commenti brevi in inglese e fix.';}));
async function detectGame(){game='';const r=await request('/device',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({port:$('adb-port').value,serial:$('adb-serial').value})});const d=await r.json();if(!d.package||d.package.includes('launcher'))throw new Error('Apri il gioco in MuMu e riprova.');game=d.package;$('game-name').textContent=game+' · '+(d.serial||'');$('detect-game').textContent='Gioco rilevato ✓';return game;}
for(const id of ['adb-port','adb-serial'])$(id).addEventListener('input',()=>{game='';$('detect-game').textContent='Rileva il gioco aperto ↻';});
async function deviceError(error){notice(error.message);$('diagnostics').open=true;await refreshLog();}
$('detect-game').addEventListener('click',async()=>{notice('');$('detect-game').disabled=true;try{await detectGame();}catch(e){await deviceError(e);}finally{$('detect-game').disabled=false;}});
$('job-form').addEventListener('submit',async e=>{e.preventDefault();notice('');if(!file)return notice('Carica l’Excel del cliente.');busy=true;connected(!!token);try{
 if(!game)await detectGame();
 const options={mode:document.querySelector('[name=mode]:checked').value,language:$('language').value==='other'?$('other-language').value.trim():$('language').value,package:game,allow_game_progress:$('progress-game').checked,max_calls:Number($('max-calls').value)};
 const r=await request('/jobs',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Filename':encodeURIComponent(file.name),'X-Options':encodeURIComponent(JSON.stringify(options))},body:file});render(await r.json());
}catch(e){busy=false;connected(!!token);await deviceError(e);}});
function render(job){if(!job)return;showImport(job);$('result').hidden=false;busy=['running','importing','stopping'].includes(job.status);connected(!!token);$('stop').hidden=!busy;$('stop').disabled=job.status==='stopping';$('result-title').textContent=({importing:'Lettura dell’Excel',running:'Il bot sta lavorando',stopping:'Arresto in corso',complete:'Pronto per la revisione',partial:'Risultato parziale',error:'Il lavoro richiede attenzione',interrupted:'Lavoro interrotto'})[job.status]||job.status;$('result-message').textContent=job.message;
 const u=job.usage;const n=v=>Number(v||0).toLocaleString('it-IT');if(u){$('token-total').textContent=n(u.total_tokens);$('token-detail').textContent=`Input ${n(u.input_tokens)} (cache ${n(u.cached_input_tokens)}) · Output ${n(u.output_tokens)} · Excel ${n(u.groups.planning.input_tokens+u.groups.planning.output_tokens)} · Testing ${n(u.groups.testing.input_tokens+u.groups.testing.output_tokens)}`;$('token-note').textContent=u.unreported_calls?`Conteggio parziale: ${n(u.unreported_calls)} chiamate in corso o senza dati token disponibili. La cache è già inclusa nell’input.`:'Token comunicati da Codex per questo progetto, aggiornati dopo ogni chiamata. Cache già inclusa nell’input; non è il saldo dell’account.';}else{$('token-total').textContent='—';$('token-detail').textContent='Contatore non disponibile: aggiorna il componente Windows.';}
 const p=job.progress;$('progress-bar').style.width=(job.status==='complete'?100:p&&p.total?Math.round(100*p.completed/p.total):busy?8:0)+'%';$('progress-text').textContent=p?`${p.completed} di ${p.total} obiettivi completati · ${p.calls} chiamate di testing`:'';
 $('downloads').replaceChildren();for(const d of job.downloads||[]){const b=document.createElement('button');b.type='button';b.textContent=(d.kind==='excel'?'Scarica Excel':d.name)+(d.partial?' · parziale':'');b.addEventListener('click',async()=>{b.disabled=true;try{const r=await request('/download/'+encodeURIComponent(d.key));const u=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=u;a.download=d.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),60000);}catch(e){notice(e.message);}finally{b.disabled=false;}});$('downloads').append(b);}}
async function poll(){if(!token||polling)return;polling=true;try{const r=await request('/status');const data=await r.json();companionVersion=data.version||'0.4.0';connected(true);render(data.job);if(!compatible())notice('Per analizzare Excel con strutture diverse serve il componente Windows 0.5.0 o successivo. Chiudi quello vecchio e apri il nuovo ZIP scaricato dal sito.');}catch(e){connected(false);notice(e.message);}finally{polling=false;}}
$('stop').addEventListener('click',async()=>{try{await request('/stop',{method:'POST'});await poll();}catch(e){notice(e.message);}});
if(token)poll();setInterval(()=>{if(token)poll();},3000);
async function refreshLog(){try{const r=await request('/diagnostics');const d=await r.json();$('error-log').textContent=d.log;$('log-status').textContent='Componente Windows '+d.version;return d.log;}catch(e){$('log-status').textContent=e.message+' Se il componente è precedente alla versione 0.4.1, scarica il nuovo ZIP.';return null;}}
$('refresh-log').addEventListener('click',refreshLog);
$('download-log').addEventListener('click',async()=>{const log=await refreshLog();if(log===null)return;const url=URL.createObjectURL(new Blob([log],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='LQA-Pilot-diagnostics.log';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);});
